version: '3.8'
services:
  app:
    build:
      context: .
      args:
        REMIX_TOKEN: '${REMIX_TOKEN}'
    container_name: very-short
    depends_on:
      - db
      - pgadmin
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
        DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres_container:5432/${POSTGRES_DB}
    ports:
      - '3000:3000'

  db:
    container_name: postgres_container
    logging:
      driver: none
    image: postgres
    restart: always
    env_file:
      - .env
    environment:
      PGDATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin4_container
    logging:
      driver: none
    image: dpage/pgadmin4:latest
    restart: always
    env_file:
      - .env
    environment:
      PGADMIN_DEFAULT_EMAIL: ${POSTGRES_USER}@${POSTGRES_USER}.com
      PGADMIN_DEFAULT_PASSWORD: ${POSTGRES_PASSWORD}
      PGADMIN_LISTEN_PORT: 80
    ports:
      - '8080:80'
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  db-data:
  pgadmin-data:
