name: Fly.io Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions@master
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          REMIX_TOKEN: ${{ secrets.REMIX_TOKEN }}
        with:
          args: 'deploy --build-arg REMIX_TOKEN=${REMIX_TOKEN}'
