name: Fly.io Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
env:
  NODE_VERSION: '14.x'
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  REMIX_TOKEN: ${{ secrets.REMIX_TOKEN }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
      - run: npm install
      - run: npm run build
      - run: npm run deploy
